/**
 * Library
 * The library API description
 *
 * OpenAPI spec version: 1.0
 * Contact: drmrhdt@mail.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UpdateTagDto { 
    /**
     * The tag's name
     */
    name: string;
}